# coding: utf-8

"""
    Mouni Expense Manager API

    Simple API to manage group expenses and settle balances.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from api_server.apis.activities_api import router as ActivitiesApiRouter
from api_server.apis.expenses_api import router as ExpensesApiRouter
from api_server.apis.groups_api import router as GroupsApiRouter
from api_server.apis.members_api import router as MembersApiRouter
from api_server.apis.settlements_api import router as SettlementsApiRouter

app = FastAPI(
    title="Mouni Expense Manager API",
    description="Simple API to manage group expenses and settle balances.",
    version="1.0.0",
)

app.include_router(ActivitiesApiRouter)
app.include_router(ExpensesApiRouter)
app.include_router(GroupsApiRouter)
app.include_router(MembersApiRouter)
app.include_router(SettlementsApiRouter)
