# coding: utf-8

"""
    Mouni Expense Manager API

    Simple API to manage group expenses and settle balances.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Union

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    StrictBool,
    StrictStr,
    field_validator,
)
from typing_extensions import Annotated

from api_server.models.expense_involved import ExpenseInvolved

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class ExpenseUpdate(BaseModel):
    """
    ExpenseUpdate
    """ # noqa: E501
    description: Annotated[str, Field(min_length=3, strict=True)]
    amount: Union[Annotated[float, Field(strict=True, ge=1)], Annotated[int, Field(strict=True, ge=1)]]
    currency: Annotated[str, Field(min_length=3, strict=True)]
    paid_by: StrictStr = Field(description="Member ID who paid", alias="paidBy")
    involved: List[ExpenseInvolved]
    equal_split: Optional[StrictBool] = Field(default=True, description="If true, ignore any shares provided in `involved` and split equally. If false, each involved entry must include a share. ", alias="equalSplit")
    var_date: datetime = Field(alias="date")
    __properties: ClassVar[List[str]] = ["description", "amount", "currency", "paidBy", "involved", "equalSplit", "date"]

    @field_validator('currency')
    def currency_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('JPY', 'USD', 'EUR', 'GBP', 'AUD', 'CAD', 'CHF', 'CNY', 'HKD', 'SGD',):
            raise ValueError("must be one of enum values ('JPY', 'USD', 'EUR', 'GBP', 'AUD', 'CAD', 'CHF', 'CNY', 'HKD', 'SGD')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExpenseUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in involved (list)
        _items = []
        if self.involved:
            for _item in self.involved:
                if _item:
                    _items.append(_item.to_dict())
            _dict['involved'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of ExpenseUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "description": obj.get("description"),
            "amount": obj.get("amount"),
            "currency": obj.get("currency") if obj.get("currency") is not None else 'JPY',
            "paidBy": obj.get("paidBy"),
            "involved": [ExpenseInvolved.from_dict(_item) for _item in obj.get("involved")] if obj.get("involved") is not None else None,
            "equalSplit": obj.get("equalSplit") if obj.get("equalSplit") is not None else True,
            "date": obj.get("date")
        })
        return _obj


